name: nextjs-dev
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - UI_URL=http://localhost:3000
    ports:
      - 8000:8080
    volumes:
      - ./api/:/app
      - /app/obj/
      - /app/bin/
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - 3000:3000
    volumes:
      - ./ui/:/app
      - /app/node_modules
